### ISSUE TITLE
opencadd conda package

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/opencadd#97]
## Description

Add `opencadd` to `conda-forge`.

## TODOs

- [x] Submit `conda` recipe: https://github.com/conda-forge/staged-recipes/pull/16114

## Questions

- [x] Problem: `muscle` lives only on `bioconda`
- [x] Problem: `theseus` and `mmligner` are not available for Windows (https://github.com/volkamerlab/opencadd/issues/11)
  - `conda-forge` recipe skips Windows. Can we avoid this for `opencadd`? https://github.com/volkamerlab/opencadd/blob/3c2e78753916f0dbba23f3ba7fc7f93f4bbbdf04/devtools/conda-recipes/theseus/meta.yaml#L12-L13 
- [x] Who will co-maintain this package? Jaime :)

**Comment by jaimergp** [comment]
`opencadd` will be a `noarch` package, which means we cannot skip platforms. Some platforms won't have all dependencies and fail to install. If we do want clean installs for all platforms, `muscle`, `theseus` and `mmligner` should be soft imports (guarded in a try/except clause, with appropriate messages if needed).

You can add me as a co-maintainer.

**Comment by dominiquesydow** [comment]
> If we do want clean installs for all platforms, muscle, theseus and mmligner should be soft imports (guarded in a try/except clause, with appropriate messages if needed).

@jaimergp where do I add these soft imports? In the package code we do not import these packages directly I think (e.g. `import theseus`). They are executed from the command-line, aren't they (with `subprocess`)?

**Comment by jaimergp** [comment]
Oh, true. We might need to add a check to see if the are in PATH, or just let it fail :D

**Comment by dominiquesydow** [comment]
`opencadd` conda package is out: https://anaconda.org/conda-forge/opencadd
